<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>9e7664ce-30fd-4776-957b-8bfcd8f63171</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ReferenceDessin.Application\ReferenceDessin.Application.csproj" />
      <ProjectReference Include="..\ReferenceDessin.Infrastructure\ReferenceDessin.Infrastructure.csproj" />
    </ItemGroup>

</Project>
